# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a5b65889f1decddd760546b3ba5a05611e55495bb8ec88e688a4e6289d0f2333a6a15f19007a428078edf1309282e6b74b36d26d3ef97cf5905a20d1f86f37b

test:
  secret_key_base: 390e0c662c5e5db3dae57d82761b8e817713f3617bc9c579ba9b48c1d512ec007ec8b907adfa8523e4481ae4af252aef6e1ac7d4dfa0e44716817598e5c8479e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
